### ISSUE TITLE
Loading separate scripts for each page?

### ISSUE THREAD

**Issue by dannymout** [armandsalle/vite-javascript-webflow#2]
I'm newer to JS build tools/modules. Would I need to create separate modules for each page of my Webflow project?

My first thought is to call a function in main.js, depending on the current path.

**Comment by dannymout** [comment]
Re-opening this because I'm interested in how you handled this?

I've been checking page path in `main.js` and importing functions from files for each of my Webflow pages. It works alright, but it's not ideal because you're importing the code for all your pages even though it won't be used.

**Comment by armandsalle** [comment]
Hey!

You can handle that two different ways:
- Customize the Vite config to use multiple files and build multiple files (not my preferred way)
- Use dynamic import from your main router to load the JS code needed for the page your users will be

https://vitejs.dev/guide/features#glob-import

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import#import_a_module_for_its_side_effects_only

**Comment by dannymout** [comment]
ahh I see, if I dynamic import all my page modules, Vite will split up the files.
