### ISSUE TITLE
Prevent cache on prod

### ISSUE THREAD

**Issue by c0c0t3** [armandsalle/vite-javascript-webflow#4]
Hello Armand,

Sometimes, clients, project manager, users... has cached the dist js file generated.

I made this :

const d = new Date();
let seconds = d.getSeconds();
const PROD_URL = ['my_dist_url.js?'+ seconds]

What do you think ?

**Comment by Armand-Salle-Dalma** [comment]
Hey! If it's working it's a good idea.
You can make a PR to update the doc, and create another PR for the TS project

**Comment by armandsalle** [comment]
Hey! If it's working it's a good idea.
You can make a PR to update the doc, and create another PR for the TS project
