### ISSUE TITLE
Cannot use import statement outside a module?

### ISSUE THREAD

**Issue by Fergie77** [armandsalle/vite-javascript-webflow#6]
I've been trying to implement this but am having a problem when bringing the code through from Netlify. It gives me the error

Uncaught SyntaxError: Cannot use import statement outside a module

Which reading the code I'm presuming is because dev mode is being set to false for production and the script is being loaded not as a module, so it doesn't like an import being in the code. What am I doing wrong? Also I notice that vite is loaded locally but not in production, is this right?

Code is here

```
(function () {
    const LOCALHOST_URL = [
    	'http://localhost:3000/@vite/client',
      'http://localhost:3000/src/homepage.js',
    ]
    const PROD_URL = ['https://buttermilk-tg.netlify.app/homepage.js']
    
function createScripts(arr, isDevMode) {
      return arr.map(function (url) {
        const s = document.createElement('script')
        s.src = url

        if (isDevMode) {
          s.type = 'module'
        }

        return s
      })
    }

    function insertScript(scriptArr) {
      scriptArr.forEach(function (script) {
        document.body.appendChild(script)
      })
    }

    const localhostScripts = createScripts(LOCALHOST_URL, true)
    const prodScripts = createScripts(PROD_URL, false)

    let choosedScripts = null

    fetch(LOCALHOST_URL[0], {})
      .then(() => {
        choosedScripts = localhostScripts
      })
      .catch((e) => {
        choosedScripts = prodScripts
        console.error(e)
      })
      .finally(() => {
        if (choosedScripts) {
          insertScript(choosedScripts)

          return
        }

        console.error('something went wrong, no scripts loaded')
      })
  })()
```

**Comment by armandsalle** [comment]
Hello!

Yes it looks like this is a problem with the `type="module"` on the script tag. We want it only in dev mode, when the code is load from your localhost (your computer when you do `yarn dev`). In production mode, when Netlify build the code, it converts the module code to a not module code base. So this is weird that you have this issue... 🧐

Can I have a preview link (not the designer page, the .webflow.io link) please?
