### ISSUE TITLE
Can't deploy with Netlify

### ISSUE THREAD

**Issue by OversensitiveCat** [armandsalle/vite-javascript-webflow#7]
Hey, 

First of all, thanks a lot for your work. I'm using your template for a few projects and it's been very helpful.
I'm encountering a new issue when I'm deploying my website with Netlify (it was working perfectly until now):

error An unexpected error occurred: "Invalid value type 100:0 in /opt/build/repo/yarn.lock".

Do you have any idea of where it could come from?

Thanks a lot.

**Comment by armandsalle** [comment]
Hello! 👋 thank you for your words ❤️ 

Yes the `yarn.lock` file is generated based on the dependencies you need for your project. You can delete it and run `yarn`, it should fix the issue.
