### ISSUE TITLE
Blocked by CORS policy

### ISSUE THREAD

**Issue by wip-com** [armandsalle/vite-javascript-webflow#8]
Hi,
First of all, thank you very much for your work. 
I have an issue with the netlify link. When I work locally with http://localhost:3000... everything works. I publish on netlify and change my script with that of netlify but I have a loading error. The script don't load with this error in the console : has been blocked by CORS policy: No 'Access-Control-Allow-Origin'. Do you know how to resolve this problem ?

**Comment by wip-com** [comment]
I fixed the issue by removing the type="module" attribute in the script tag on webflow. 
On the other hand, instead of using a single main.js script I would like to use different scripts depending on the page (home.js, about.js etc.). Is this possible with your workflow. I tried to modify the vite.config.js but I can't get the desired result.

**Comment by chigggsy** [comment]
@wip-com I'm new to dev and currently looking for the same solution. I've currently come up with a very scrappy solution. I'll create home.js, about.js, etc. Inside I'll contain everything inside a function (e.g. `const pageAbout = () => {//The code for the page...} `. Then at the bottom export it: `export default pageAbout`

Then in the main.js, I'll import it at the top: `import pageAbout from './pages/pageAbout'` and then with an if-else statement, calling the correct function according to the url pathname. So: `if (window.location.pathname === '/about') {
  aboutAbout()`
  
While this is working, it's very manual and tedious to create and manage for multiple pages. So I'm currently on the look out for a more effective way to automate this process. 

@armandsalle What would your thoughts be on the right way to do this?

**Comment by armandsalle** [comment]
Hey @chigggsy 👋 yes I understand what you want, but as Webflow does a full reload on navigation (browser normal behavior) we need a way to check on what page we currently are. So I'll use some conditions on `window.location.pathname` to run some code or not.

That's not the best way, but it works and it is pretty clear and easy to understand

**Comment by chigggsy** [comment]
@armandsalle Appreciate the quick reply! Cheers!
